### ISSUE TITLE
Erroneous example in README

### ISSUE THREAD

**Issue by tlhunter** [opentable/spur-web#18]
The registerConfig line in this file is incorrect:
https://github.com/opentable/spur-web#srcinjectorcoffee

should it instead be spurCommon.registerConfig? I didn't dive into it too deeply.

**Comment by acolchado** [comment]
Resolved as part of https://github.com/opentable/spur-web/pull/22

Added a working example that was used to copy code examples into the read me file.

Will be published with the next release.
